[package]
name = "ludumdare42"
version = "0.1.0"
authors = ["The Amethyst team for Ludum Dare 42"]

[dependencies]
amethyst = { path = "../amethyst" }
amethyst-extra = { git = "https://github.com/jojolepro/amethyst-extra.git" }